#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: validate_k8s_params.yml
os_supported_rhel: "redhat"
os_supported_rocky: "rocky"
k8s_pkgs:
  - yum-plugin-versionlock
  - python3-netaddr
success_msg_k8s_pod_network_cidr: "Appliance k8s pod network cidr validated"
fail_msg_k8s_pod_network_cidr: "Failed. Incorrect appliance k8s pod network cidr provided in monitor_config.yml"
utils_collection: ansible.utils:2.5.2
pip_version: pip3.8

# Usage: validate_grafana_params.yml
fail_msg_grafana_credentials: "Failed. Incorrect grafana_username or grafana_password provided in input/telemetry_config.yml"
mount_validation_msg: "Make sure mount location value is given in correct format."
min_length_grafana: 5
max_length: 30
selinux_warning: "Warning! SELinux status is disabled by user. No SELinux policy is loaded"
os_supported_leap: "leap"

# Usage: k8s_installation_leap.yml
k8s_repo_leap: https://pkgs.k8s.io/core:/stable:/v1.26/rpm/
rpm_pkg_leap: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
yum_key_leap: https://packages.cloud.google.com/yum/doc/yum-key.gpg
gpg_pubkey_leap: "rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}'"
docker_repo_url_leap: https://download.docker.com/linux/sles/docker-ce.repo
docker_repo_dest_leap: /etc/YaST2/docker-ce.repo
kubeadm_version: kubeadm-1.26.0-0.x86_64
kubelet_version: kubelet-1.26.0-0.x86_64
kubectl_version: kubectl-1.26.0-0.x86_64
os_supported_leap_version: "15.3"
min_retries: 3
max_retries: 10
min_delay: 10
wait_time: 30
crio_repo_leap: "https://download.opensuse.org/repositories/devel:kubic/15.3/devel:kubic.repo"
k8s_package_names:
  - kubeadm
  - kubelet
  - kubectl
version_kubectl: "v1.26.0"

# Usage: k8s_installation.yml
k8s_common_packages_rocky:
  - openssl
  - bash-completion
  - cri-o
  - buildah
k8s_common_packages_rhel:
  - openssl
  - bash-completion
  - buildah
k8s_packages:
  - kubelet-1.26.0
  - kubeadm-1.26.0
  - kubectl-1.26.0
k8s_conf_dest: /etc/modules-load.d/
crio_conf_dest: /etc/modules-load.d/
k8s_crio_conf_dest: /etc/sysctl.d/
crio_repo1_url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
crio_repo1_dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
crio_repo2_url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21:/1.21.7/CentOS_8/
crio_repo2_dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.21.repo
crio_repo2_gpg: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21:/1.21.7/CentOS_8/repodata/repomd.xml.key
docker_repo_url: https://download.docker.com/linux/centos/docker-ce.repo
docker_repo_dest: /etc/yum.repos.d/docker-ce.repo
crio_repo: "devel:kubic:libcontainers:stable:cri-o:1.21,rhel-8-for-x86_64-appstream-rpms,rhel-8-for-x86_64-baseos-rpms"
file_mode: 0700
docker_cli_package: docker-ce-cli-24.0.4
retry_count: 3

# Usage: k8s_firewalld.yml
k8s_master_ports:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250/tcp
  - 10251/tcp
  - 10252/tcp
  - 10255/tcp
  - 8472/udp
  - 30000-32767/tcp
calico_udp_ports:
  - 4789
calico_tcp_ports:
  - 5473
  - 179

# Usage: k8s_helm.yml
helm_installer_file_directory: /root/bin
helm_installer_file_directory_mode: 0755
helm_installer_url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
helm_installer_file_dest: /root/bin/get_helm.sh
helm_installer_file_mode: 0700
helm_stable_repo_url: https://charts.helm.sh/stable

# Usage: k8s_init.yml
k8s_root_directory: /root/.kube
k8s_root_directory_mode: 0755
k8s_config_src: /etc/kubernetes/admin.conf
k8s_config_dest: /root/.kube/config
k8s_config_file_mode: 0644
k8s_cert_path: /etc/kubernetes/pki/ca.crt
yaml_repo_dir_path: /root/k8s
yaml_repo_dir_mode: 0755
tigera_operator_url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
calico_yml_url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml
crio_socket_path: /var/run/crio/crio.sock
policy_file: /etc/containers/policy.json

# Usage: configure_metallb.yml
ipaddresspool_file_src: "{{ role_path }}/files/ipaddresspool.yaml"
metallb_ipaddresspool_file_dest: /var/lib/ipaddresspool.yaml
metallb_file_owner: root
metallb_group_owner: root
metallb_ipaddresspool_file_mode: 0655
l2advertisement_file_src: "{{ role_path }}/files/l2advertisement.yaml"
metallb_l2advertisement_file_dest: /var/lib/l2advertisement.yaml
metallb_l2advertisement_file_mode: 0655
metallb_yaml_url: https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/manifests/metallb-native.yaml
metallb_wait_time: 120

# Usage: k8s_services.yml
k8s_dashboard_yaml_url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml
k8s_dashboard_admin_file_dest: /root/k8s/k8s_dashboard_admin.yaml
k8s_dashboard_admin_file_mode: 0655
nfs_path: /var/nfs_repo
vault_file_perm: '0644'

# Usage: nfs_server_setup.yml
nfs_share_offline_repo: /var/nfs_repo
nfs_share_dir_mode: 0777
exports_file_path: /etc/exports
nfs_services:
  - mountd
  - rpc-bind
  - nfs

# Usage: prerequisites.yml
rocky_version: "8.7"
redhat_version: "8.7"
keypath_str: '"keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"'
policy_file_path: "/etc/containers/policy.json"

# Usage: k8s_secrets.yml
namespace: telemetry-and-visualizations
secrets_name: credentials
